### ISSUE TITLE
Any examples how to get started?

### ISSUE THREAD

**Issue by hanneslinder** [david-sawatzke/hub75-rs#8]
I'm pretty new with Rust and I am a bit lost trying to get your code to run. 
It would be very nice if you could provide a simple example on how to get started.
Thanks :)

**Comment by david-sawatzke** [comment]
I used this crate here: https://github.com/david-sawatzke/36c3_led_stuff/commit/fc6e59c7bb36ee8c4f407e93038ee7fa6fa38f5d, before changing to a custom, more efficient implementation. 

I don't really have a good standalone example, but that might help.
